# Generated by Django 5.1.2 on 2024-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
