# Generated by Django 4.2.11 on 2025-07-24 10:29

import chatApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_room_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('uid', models.CharField(default=chatApp.models.generate_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('handle', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chatApp_anchor',
            },
        ),
        migrations.CreateModel(
            name='ChatUserChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255)),
                ('uid', models.CharField(default='0', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('user_message', models.TextField()),
                ('send_date', models.DateTimeField()),
                ('identity', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'chatApp_chatuser_chat_history',
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.AlterModelOptions(
            name='chatuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='chatuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
