# Generated by Django 4.2.11 on 2025-07-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_anchor_chatuserchathistory_remove_room_online_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatuserchathistory',
            old_name='room_id',
            new_name='room_name',
        ),
    ]
