# Generated by Django 4.2.11 on 2025-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_rename_room_id_chatuserchathistory_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_id', models.IntegerField(unique=True, verbose_name='主播ID')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='主播收到的总打赏金额')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='主播当前余额')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '主播余额',
                'verbose_name_plural': '主播余额',
                'db_table': 'anchor_balance',
            },
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('anchor_id', models.IntegerField(verbose_name='主播ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='打赏金额')),
                ('donation_date', models.DateTimeField(auto_now_add=True, verbose_name='打赏时间')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20, verbose_name='打赏状态')),
            ],
            options={
                'verbose_name': '打赏记录',
                'verbose_name_plural': '打赏记录',
                'db_table': 'donation_records',
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='充值金额')),
                ('recharge_date', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20, verbose_name='充值状态')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'recharge_records',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='用户ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='用户余额')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '用户余额',
                'verbose_name_plural': '用户余额',
                'db_table': 'user_balance',
            },
        ),
    ]
