# Generated by Django 5.2.4 on 2025-08-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_anchorbalance_donationrecord_rechargerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
