# Generated by Django 5.2.4 on 2025-08-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0008_userfollowedroom_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
