# Generated by Django 5.2.4 on 2025-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0009_remove_subscription_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorbalance',
            name='anchor_id',
            field=models.CharField(max_length=255, verbose_name='主播ID'),
        ),
    ]
