# Generated by Django 5.2.4 on 2025-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0011_alter_anchorbalance_anchor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='anchor_id',
            field=models.CharField(max_length=225, verbose_name='主播ID'),
        ),
    ]
