# Generated by Django 5.2.4 on 2025-08-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0012_alter_donationrecord_anchor_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
