# Generated by Django 5.2.4 on 2025-08-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0013_alter_subscription_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userfollowedroom',
            table='user_followed_room',
        ),
    ]
