# Generated by Django 5.2.4 on 2025-08-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0014_alter_userfollowedroom_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='用户ID')),
                ('character_name', models.CharField(max_length=255, verbose_name='角色名称')),
                ('title', models.CharField(max_length=255, verbose_name='房间标题')),
                ('coin_num', models.IntegerField(verbose_name='钻石数量')),
                ('room_type', models.SmallIntegerField(choices=[(0, 'Free'), (1, 'VIP'), (2, '1v1')], default=0, verbose_name='房间类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='房间创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='房间最后更新时间')),
            ],
            options={
                'db_table': 'room_info',
            },
        ),
    ]
