# Generated by Django 5.2.4 on 2025-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0015_roominfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipSubscriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('anchor_id', models.CharField(max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('pay_coin_num', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('vip_expiration_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'vip_subscription_record',
            },
        ),
    ]
