# Generated by Django 5.2.4 on 2025-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0016_vipsubscriptionrecord'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowedroom',
            name='unique_user_room',
        ),
        migrations.RenameField(
            model_name='userfollowedroom',
            old_name='room_id',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='vipsubscriptionrecord',
            name='vip_expiration_date',
        ),
        migrations.AlterField(
            model_name='userfollowedroom',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='userfollowedroom',
            constraint=models.UniqueConstraint(fields=('user_id', 'room_name'), name='unique_user_room'),
        ),
    ]
