# Generated by Django 5.2.4 on 2025-08-31 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0017_remove_userfollowedroom_unique_user_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='NOWPayments 支付ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='充值货币')),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='USDT充值金额')),
                ('crypto_currency', models.CharField(default='USDT', max_length=10, verbose_name='加密货币类型，固定为USDT')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='订单ID')),
                ('recharge_date', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('expired', 'Expired')], default='waiting', max_length=20, verbose_name='充值状态')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'payment_recharge_records',
            },
        ),
        migrations.RemoveField(
            model_name='anchorbalance',
            name='total_donations',
        ),
        migrations.AddField(
            model_name='anchorbalance',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='累计收入（USD等值）'),
        ),
        migrations.AddField(
            model_name='anchorbalance',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='USDT余额'),
        ),
        migrations.AddField(
            model_name='chatuserchathistory',
            name='room_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='character_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='角色卡创建时间'),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='room_id',
            field=models.CharField(max_length=255, null=True, verbose_name='房间ID'),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='room_name',
            field=models.CharField(max_length=255, null=True, verbose_name='房间名称'),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='user_name',
            field=models.CharField(max_length=255, null=True, verbose_name='主播名称'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='平台货币赠送余额（兑换优惠赠送的金额）'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='USDT余额'),
        ),
        migrations.AddField(
            model_name='userfollowedroom',
            name='room_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vipsubscriptionrecord',
            name='room_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anchorbalance',
            name='anchor_id',
            field=models.CharField(max_length=22, unique=True, verbose_name='主播ID'),
        ),
        migrations.AlterField(
            model_name='anchorbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='平台货币余额（USD等值）'),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='uid',
            field=models.CharField(max_length=255, verbose_name='主播ID'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='平台货币余额'),
        ),
        migrations.AddIndex(
            model_name='anchorbalance',
            index=models.Index(fields=['anchor_id'], name='payment_anc_anchor__e1c9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='userbalance',
            index=models.Index(fields=['user_id'], name='payment_use_user_id_035b9f_idx'),
        ),
        migrations.AlterModelTable(
            name='anchorbalance',
            table='payment_anchor_balance',
        ),
        migrations.AlterModelTable(
            name='userbalance',
            table='payment_user_balance',
        ),
    ]
