# Generated by Django 5.2.4 on 2025-09-06 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0018_paymentrechargerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentExpenditureRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('anchor_id', models.CharField(max_length=22, verbose_name='主播ID')),
                ('payment_type', models.CharField(choices=[('donation', '打赏'), ('subscription', '订阅')], max_length=20, verbose_name='支付类型')),
                ('payment_source', models.CharField(choices=[('donation', '打赏'), ('subscription', '订阅')], max_length=20, verbose_name='支付来源')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='支付金额')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='支付货币')),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='USDT支付金额')),
                ('crypto_currency', models.CharField(default='USDT', max_length=10, verbose_name='加密货币类型')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '支出,订阅记录',
                'verbose_name_plural': '支出,订阅记录',
                'db_table': 'payment_expenditure_records',
            },
        ),
        migrations.CreateModel(
            name='PaymentLiveroomEntryRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('anchor_id', models.CharField(max_length=22, verbose_name='主播ID')),
                ('room_name', models.CharField(max_length=255, verbose_name='房间名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='支付金额')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='支付货币')),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='USDT支付金额')),
                ('crypto_currency', models.CharField(default='USDT', max_length=10, verbose_name='加密货币类型')),
            ],
            options={
                'verbose_name': '直播间进入记录',
                'verbose_name_plural': '直播间进入记录',
                'db_table': 'payment_liveroom_entry_records',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('api_request', 'API请求'), ('api_response', 'API响应'), ('ipn', '回调通知'), ('error', '错误')], max_length=20, verbose_name='日志类型')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('details', models.TextField(verbose_name='日志详情')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付日志',
                'verbose_name_plural': '支付日志',
                'db_table': 'payment_logs',
            },
        ),
        migrations.AddField(
            model_name='roominfo',
            name='describe',
            field=models.CharField(max_length=255, null=True, verbose_name='房间描述'),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='is_info',
            field=models.IntegerField(null=True, verbose_name='是否添加info'),
        ),
    ]
