# Generated by Django 5.2.4 on 2025-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0019_paymentexpenditurerecord_paymentliveroomentryrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('character_name', models.CharField(max_length=150)),
                ('image_name', models.CharField(max_length=150)),
                ('image_path', models.CharField(max_length=255)),
                ('character_data', models.TextField()),
                ('create_date', models.CharField(max_length=150)),
                ('language', models.CharField(choices=[('en', 'English'), ('cn', '中文')], default='en', max_length=2, verbose_name='语言')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签（逗号分隔或JSON）')),
                ('is_private', models.BooleanField(default=False, verbose_name='是否私密')),
            ],
            options={
                'db_table': 'character_card',
            },
        ),
        migrations.DeleteModel(
            name='DonationRecord',
        ),
        migrations.DeleteModel(
            name='RechargeRecord',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='VipSubscriptionRecord',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
