# Generated by Django 5.2.4 on 2025-09-27 17:26

import chatApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0020_charactercard_delete_donationrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercard',
            name='image_path',
            field=models.ImageField(max_length=255, upload_to=chatApp.models.character_image_upload_path, verbose_name='图片存储路径'),
        ),
    ]
