# Generated by Django 5.2.4 on 2025-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0021_alter_charactercard_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='file_branch',
            field=models.CharField(max_length=255, null=True, verbose_name='文件分支'),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='file_name',
            field=models.CharField(max_length=255, null=True, verbose_name='文件名'),
        ),
    ]
