# Generated by Django 5.2.4 on 2025-10-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0022_roominfo_file_branch_roominfo_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_user_id', models.IntegerField(verbose_name='发起 fork 用户ID')),
                ('target_id', models.CharField(max_length=22, verbose_name='被 fork 用户ID')),
                ('room_id', models.CharField(max_length=255, verbose_name='原房间ID')),
                ('character_name', models.CharField(max_length=255, verbose_name='角色名')),
                ('floor', models.IntegerField(default=0, verbose_name='楼层')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Fork 关系',
                'verbose_name_plural': 'Fork 关系',
                'db_table': 'fork_relation',
            },
        ),
        migrations.AddField(
            model_name='roominfo',
            name='is_show',
            field=models.IntegerField(default=0, verbose_name='是否展示'),
        ),
    ]
