# Generated by Django 5.2.4 on 2025-10-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0023_forkrelation_roominfo_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_room_id', models.CharField(max_length=32)),
                ('source_uid', models.CharField(max_length=22)),
                ('prev_room_id', models.CharField(max_length=32)),
                ('prev_uid', models.CharField(max_length=22)),
                ('current_room_id', models.CharField(max_length=32)),
                ('current_uid', models.CharField(max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fork_trace',
            },
        ),
    ]
