# Generated by Django 5.2.4 on 2025-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0024_forktrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=150, verbose_name='用户ID')),
                ('room_id', models.CharField(max_length=150, verbose_name='角色卡 room_id')),
                ('status', models.SmallIntegerField(default=1, verbose_name='收藏状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorite',
                'unique_together': {('uid', 'room_id')},
            },
        ),
    ]
