# Generated by Django 5.2.4 on 2025-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0025_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowedroom',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
