# Generated by Django 5.2.4 on 2025-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0026_alter_userfollowedroom_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.CharField(max_length=255)),
                ('followed_id', models.CharField(max_length=255)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_follow_relation',
            },
        ),
        migrations.DeleteModel(
            name='UserFollowedRoom',
        ),
        migrations.AddConstraint(
            model_name='userfollowrelation',
            constraint=models.UniqueConstraint(fields=('follower_id', 'followed_id'), name='unique_user_follow'),
        ),
    ]
