# Generated by Django 5.2.4 on 2025-10-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0027_userfollowrelation_delete_userfollowedroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='被邀请用户ID')),
                ('referrer_id', models.BigIntegerField(verbose_name='邀请人ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邀请关系',
                'verbose_name_plural': '邀请关系',
                'db_table': 'referral_relation',
            },
        ),
    ]
