# Generated by Django 5.2.4 on 2025-10-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0028_referralrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralRelation',
        ),
    ]
