# Generated by Django 5.2.4 on 2025-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0029_delete_referralrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='referrer_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='邀请人ID'),
        ),
    ]
