# Generated by Django 5.2.4 on 2025-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0030_chatuser_referrer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDiamondFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('anchor_id', models.CharField(blank=True, max_length=22, null=True, verbose_name='主播ID')),
                ('payment_action', models.CharField(choices=[('donation', 'Donation'), ('subscription', 'Subscription'), ('room_entry', 'Room Entry'), ('gift', 'Gift'), ('other', 'Other')], max_length=20, verbose_name='消费类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='支付金额')),
                ('currency', models.CharField(default='ZS', max_length=10, verbose_name='支付货币')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='附加信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '平台币流水',
                'verbose_name_plural': '平台币流水',
                'db_table': 'payment_diamond_flow',
            },
        ),
        migrations.RemoveField(
            model_name='paymentexpenditurerecord',
            name='crypto_amount',
        ),
        migrations.RemoveField(
            model_name='paymentexpenditurerecord',
            name='crypto_currency',
        ),
        migrations.RemoveField(
            model_name='paymentliveroomentryrecord',
            name='crypto_amount',
        ),
        migrations.RemoveField(
            model_name='paymentliveroomentryrecord',
            name='crypto_currency',
        ),
        migrations.AlterField(
            model_name='paymentexpenditurerecord',
            name='currency',
            field=models.CharField(default='ZS', max_length=10, verbose_name='支付货币'),
        ),
        migrations.AlterField(
            model_name='paymentliveroomentryrecord',
            name='currency',
            field=models.CharField(default='ZS', max_length=10, verbose_name='支付货币'),
        ),
    ]
