# Generated by Django 5.2.4 on 2025-11-05 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0031_paymentdiamondflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问接口路径')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='封禁原因')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用封禁')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'IP 黑名单',
                'verbose_name_plural': 'IP 黑名单',
                'db_table': 'ip_blacklist',
            },
        ),
    ]
