# Generated by Django 5.2.4 on 2025-11-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0032_ipblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='last_ai_reply_timestamp',
            field=models.FloatField(default=0, verbose_name='最后 AI 回复时间戳'),
        ),
    ]
