# Generated by Django 5.2.4 on 2025-11-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0033_roominfo_last_ai_reply_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255, verbose_name='room_id')),
                ('preset_settings_openai', models.CharField(max_length=255, verbose_name='预设名称')),
                ('temp_openai', models.FloatField(max_length=10, verbose_name='')),
                ('top_k_openai', models.IntegerField(max_length=10, verbose_name='')),
                ('top_p_openai', models.FloatField(max_length=10, verbose_name='')),
                ('openai_max_context', models.IntegerField(max_length=10, verbose_name='')),
                ('openai_max_tokens', models.IntegerField(max_length=10, verbose_name='')),
                ('google_model', models.CharField(max_length=255, verbose_name='模型名称')),
                ('model_n', models.IntegerField(max_length=10, verbose_name='')),
                ('preset_json', models.TextField(verbose_name='')),
            ],
            options={
                'db_table': 'preset',
            },
        ),
        migrations.AlterModelOptions(
            name='charactercard',
            options={'verbose_name': '角色卡', 'verbose_name_plural': '角色卡'},
        ),
        migrations.RemoveField(
            model_name='charactercard',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='charactercard',
            name='room_id',
        ),
        migrations.AddField(
            model_name='charactercard',
            name='source',
            field=models.CharField(choices=[('st', 'ST端'), ('pt', 'PT端')], default='pt', max_length=2, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='character_data',
            field=models.TextField(verbose_name='角色数据（JSON格式）'),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='character_name',
            field=models.CharField(max_length=150, verbose_name='角色卡名称'),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='create_date',
            field=models.CharField(max_length=150, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='image_name',
            field=models.CharField(max_length=150, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='uid',
            field=models.CharField(max_length=150, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='username',
            field=models.CharField(max_length=150, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='RoomImageBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255, verbose_name='房间ID')),
                ('image_id', models.IntegerField(verbose_name='图片ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '房间默认图片绑定',
                'verbose_name_plural': '房间默认图片绑定',
                'db_table': 'room_image_binding',
                'indexes': [models.Index(fields=['room_id'], name='idx_room_id'), models.Index(fields=['image_id'], name='idx_image_id')],
            },
        ),
    ]
