# Generated by Django 5.2.4 on 2025-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0034_preset_alter_charactercard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimagebinding',
            name='uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='房间权重'),
        ),
    ]
