"""
Django settings for chatProject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# 加载 .env 文件
load_dotenv()


build_universe_url = os.getenv('build_universe_url', '')  # 默认值可选

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z=0rcea*i34a_jg=lzm8p$z$%jb#!2juohv4f=u)_%lc-*an^1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]  # 开放访问权限


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "templates/static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',        # 添加通道应用
    'chatApp', # 添加聊天应用
    'corsheaders',#添加跨域
    'rest_framework',
    'rest_framework_simplejwt',
    'social_django',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    # 'whitenoise.middleware.WhiteNoiseMiddleware', #  不用nginx访问静态
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chatApp.middleware.ip_rate_limit.IpRateLimitMiddleware'
]

# 启用压缩和缓存（可选）
# 不用nginx访问静态
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



ROOT_URLCONF = 'chatProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOW_ALL_ORIGINS = True

WSGI_APPLICATION = 'chatProject.wsgi.application'
ASGI_APPLICATION = 'chatProject.asgi.application'  # 添加异步应用支持


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL 引擎
        'NAME': 'Pecktra',                        # 数据库名称
        'USER': 'root',                      # 用户名
        'PASSWORD': 'Tura1050493761@',              # 密码
        'HOST': 'localhost',                   # 主机地址
        'PORT': '3306',                        # 端口号
        'OPTIONS': {
            'charset': 'utf8mb4',              # 推荐使用 utf8mb4 以支持表情符号
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

# django-redis 配置
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/0',  # Redis 连接字符串
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    },
    # session 缓存配置
    'session': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/1',  # 使用相同的 Redis 实例
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    },
    'subscribe': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/2',  # 使用相同的 Redis 实例
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    },
    'chat-limit': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/3',  # 使用相同的 Redis 实例
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    },
    'chat-online': {
              'BACKEND': 'django_redis.cache.RedisCache',
              'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/4',  # 用4号DB专门存在线人数
              'OPTIONS': {
                  'CLIENT_CLASS': 'django_redis.client.DefaultClient',
              },
          }

}


MONGO_URI = os.getenv("MONGO_URI")
MONGO_DB_NAME = "chat_db"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 指定用户模型
AUTH_USER_MODEL="chatApp.ChatUser"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'chatApp.api.auth.CsrfExemptSessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


# 设置登陆、登出页面
from django.urls import reverse_lazy
LOGIN_REDIRECT_URL = reverse_lazy('login')
LOGIN_URL = reverse_lazy('login')

# 用于图像上传
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
SITE_DOMAIN = os.getenv("SITE_DOMAIN", "http://127.0.0.1:8000")

# 通道存储设置
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(f"redis://{REDIS_HOST}:{REDIS_PORT}/10")],  # Redis 地址
            "capacity": 1500,  # 默认 100，生产环境建议调大
            "expiry": 10,      # 消息过期时间（秒）
        },
    },
}

# Google OAuth2 配置
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI")


SIMPLE_JWT = {
    # 访问令牌有效期（Access Token）
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    # 刷新令牌有效期（Refresh Token）
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'pecktra',  # 使用项目的 SECRET_KEY 进行签名

    # 如果你的前端是跨域请求
    'AUTH_HEADER_TYPES': ('Bearer',),  # 前端请求头格式: Authorization: Bearer <token>
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # 其他认证后端...
]

#支付key
NOWPAYMENTS_API_KEY = os.getenv("NOWPAYMENTS_API_KEY")
NOWPAYMENTS_IPN_SECRET_KEY = os.getenv("NOWPAYMENTS_IPN_SECRET_KEY")
NOWPAYMENTS_IPN_CALLBACK_URL = os.getenv("NOWPAYMENTS_IPN_CALLBACK_URL")